EXPERIMENT_NAME: 'vgg16_nddr_sing_flat_nddr_fc8_lr_double_wd_3000_steps'
TRAIN:
  STEPS: 30001
  WEIGHT_1: 'Seg'
  WEIGHT_2: 'Normal'
  NDDR_FACTOR: 1.
  FC8_WEIGHT_FACTOR: 1.
  FC8_BIAS_FACTOR: 1.
  WEIGHT_DECAY: 5e-4
